# -*- coding: utf-8 -*-
"""water_quality_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Dbx1WlhUMDgq90BXA5IpVhYS5la56xc
"""



"""### Load Data"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/DinukaSanjana/Water-Quality-Monitoring/refs/heads/main/water_potability_csv.csv')
df

"""### Data Separation"""

y = df['Potability']
y

x = df.drop('Potability', axis=1)
x

y = df['Potability']
y

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

x_test

"""## Model Building

### Linear Regression
"""

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

"""### Apply the model to make a prediction"""

y_lr_train_pred = lr.predict(x_train)
y_lr_test_pred = lr.predict(x_test)

print(y_lr_train_pred, y_lr_test_pred)

y_lr_test_pred

"""### Evaluate model performance"""

from sklearn.metrics import mean_squared_error, r2_score

lr_train_mea = mean_squared_error(y_train, y_lr_train_pred)
lr_train_r2 = r2_score(y_train, y_lr_train_pred)

lr_test_mea = mean_squared_error(y_test, y_lr_test_pred)
lr_test_r2 = r2_score(y_test, y_lr_test_pred)

print('LR MSE (Train) : ' ,lr_train_mea)
print('LR R2 (Train) : ' ,lr_train_r2)
print('LR MSE (Test) : ' ,lr_test_mea)
print('LR R2 (Test) : ' ,lr_test_r2)

results = pd.DataFrame(['Linear Regression', lr_train_mea, lr_train_r2, lr_test_mea, lr_test_r2]).transpose()

results

